apiVersion: v1
kind: Service
metadata:
  name: sahw2-db
  labels:
    app: sahw2-db
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: sahw2-db

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sahw2-db-statefulset
spec:
  serviceName: "sahw2-db"
  replicas: 1
  selector:
    matchLabels:
      app: sahw2-db
  template:
    metadata:
      labels:
        app: sahw2-db
    spec:
      containers:
      - name: sahw2-db
        image: postgres:10.11-alpine
        ports:
        - containerPort: 5432
          name: sahw2db
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: sahw2-secret
                key: POSTGRES_DB
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sahw2-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: sahw2-secret
                key: POSTGRES_USER
        volumeMounts:
        - name: sahw2db
          mountPath: /var/lib/postgresql/data
          subPath: sahw2-db
  volumeClaimTemplates:
  - metadata:
      name: sahw2db
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
